baseURL: https://blog.lekwati.com/
languageCode: en-gb
theme: PaperMod
paginate: 5
title: Shannan's Write-y Things
disqusShortname: shannans-write-y-things

params:
  comments: true
  ShowReadingTime: true
