baseURL: https://blog.lekwati.com/
languageCode: en-gb
theme: PaperMod
paginate: 5
title: Shannan's Write-y Things
disqusShortname: shannans-write-y-things
Copyright: |
  &copy; 2020 Shannan Lekwati ([Source](https://github.com/slekwati/blog.lekwati.com))

params:
  comments: true
  ShowReadingTime: true
